// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9eZidAW0frbT5MR_JSoJdgVOptmBjNpo',
    appId: '1:143578923013:web:df86c0cc481e33daa81c6c',
    messagingSenderId: '143578923013',
    projectId: 'habit-tracker-7af81',
    authDomain: 'habit-tracker-7af81.firebaseapp.com',
    storageBucket: 'habit-tracker-7af81.firebasestorage.app',
    measurementId: 'G-5SQFFXR6T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2bWkz3Web2_sYzrMQpqE1H_jCi8w6h9o',
    appId: '1:143578923013:android:41ce43c729449732a81c6c',
    messagingSenderId: '143578923013',
    projectId: 'habit-tracker-7af81',
    storageBucket: 'habit-tracker-7af81.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9eZidAW0frbT5MR_JSoJdgVOptmBjNpo',
    appId: '1:143578923013:web:c2e8ee04a427a384a81c6c',
    messagingSenderId: '143578923013',
    projectId: 'habit-tracker-7af81',
    authDomain: 'habit-tracker-7af81.firebaseapp.com',
    storageBucket: 'habit-tracker-7af81.firebasestorage.app',
    measurementId: 'G-H5PMFPBHLE',
  );

}